collections:
  cesm:
    collection_columns:
    - resource
    - resource_type
    - direct_access
    - experiment
    - case
    - component
    - stream
    - variable
    - date_range
    - ensemble
    - file_fullpath
    - file_basename
    - file_dirname
    - ctrl_branch_year
    - year_offset
    - sequence_order
    - has_ocean_bgc
    - grid
    order_by_columns:
      - sequence_order
      - file_fullpath
    required_columns:
      - sequence_order
      - file_fullpath
    component_streams:
      atm:
      - cam.h0
      - cam.h1
      - cam.h2
      - cam.h3
      - cam.h4
      - cam.h5
      - cam.h6
      - cam.h7
      - cam.h8
      glc:
      - cism.h
      - cism.h0
      - cism.h1
      - cism.h2
      - cism.h3
      - cism.h4
      - cism.h5
      - cism.h6
      - cism.h7
      - cism.h8
      ice:
      - cice.h2_06h
      - cice.h1
      - cice.h
      lnd:
      - clm2.h0
      - clm2.h1
      - clm2.h2
      - clm2.h3
      - clm2.h4
      - clm2.h5
      - clm2.h6
      - clm2.h7
      - clm2.h8
      ocn:
      - pop.h.nday1
      - pop.h.nyear1
      - pop.h.ecosys.nday1
      - pop.h.ecosys.nyear1
      - pop.h
      - pop.h.sigma
      rof:
      - rtm.h0
      - rtm.h1
      - rtm.h2
      - rtm.h3
      - rtm.h4
      - rtm.h5
      - rtm.h6
      - rtm.h7
      - rtm.h8
      - mosart.h0
      - mosart.h1
      - mosart.h2
      - mosart.h3
      - mosart.h4
      - mosart.h5
      - mosart.h6
      - mosart.h7
      - mosart.h8
    replacements:
      freq:
        daily: day_1
        monthly: month_1
        yearly: year_1
  cmip:
    collection_columns:
    - ensemble
    - experiment
    - file_basename
    - file_fullpath
    - frequency
    - institution
    - model
    - realm
    - files_dirname
    - variable
    - version
    required_columns:
      - realm
      - frequency
      - ensemble
      - experiment
      - file_fullpath
    frequencies:
      - 3hr
      - 6hr
      - day
      - fx
      - mon
      - monclim
      - subhr
      - yr
    realms:
      - aerosol
      - atmos
      - atmoschem
      - land
      - landice
      - ocean
      - ocnbgchem
      - seaIce
default_chunk_size: 128MiB
data_cache_directory: ~/.intake_esm/data_cache
database_directory: ~/.intake_esm/collections
sources:
  cesm: intake_esm.cesm.CESMSource
  cmip: intake_esm.cmip.CMIPSource
