name: intake-esm-doc
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cftime
  - dask >=2024.12
  - distributed
  - ecgtools >=2022.10.7
  - fsspec >=2024.12
  - gcsfs >=2024.12
  - intake >=2.0
  - itables
  - jupyterlab
  - matplotlib
  - myst-nb
  - netcdf4 >=1.5.5,!=1.6.1
  - pandas >=2.1.0
  - polars>=1.24.0,<1.33.0
  - pip
  - pydantic>=2.0
  - python-graphviz
  - python=3.11
  - s3fs >=2024.12
  - setuptools >=75.0.0
  - setuptools_scm >=8.1.0
  - sphinx ==5.3.0
  - sphinx-copybutton
  - sphinx-design
  - watermark
  - xarray-datatree >=0.0.9
  - xarray >=2024.10
  - zarr <3.0|>=3.0.10
  - furo >=2022.09.15
  - kerchunk >=0.2.9
  - pip:
      - git+https://github.com/ncar-xdev/ecgtools
      - sphinxext-opengraph<0.10.0
      - -e ..
