name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - intake-xarray>=0.3.1
  - pip
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-xdist
  - pyyaml
  - toolz
  - zarr
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/intake/filesystem_spec.git
    - git+https://github.com/dask/gcsfs.git
    - git+https://github.com/dask/s3fs.git
