name: intake-esm-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - boto3
  - cartopy
  - cftime
  - codecov
  - fastprogress>= 1.0.0
  - h5netcdf>=0.8.1
  - ipython
  - matplotlib
  - netcdf4>=1.5.5
  - pandas
  - pip
  - pooch
  - pre-commit
  - psutil
  - pydantic
  - pyproj
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-sugar
  - pytest-xdist
  - regionmask
  - scipy
  - toolz
  - xgcm
  - zarr>=2.5
  - pip:
      - git+https://github.com/intake/filesystem_spec.git
      - git+https://github.com/intake/intake.git
      - git+https://github.com/dask/gcsfs.git
      - git+https://github.com/dask/s3fs.git
      - git+https://github.com/pydata/xarray.git
      - git+https://github.com/jbusecke/cmip6_preprocessing.git
      - -r ../requirements.txt
