name: intake-esm-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - cftime
  - codecov
  - dask>=2022.02.0
  - fastprogress>=1.0.0
  - gcsfs
  - h5netcdf>=0.8.1
  - ipython
  - matplotlib
  - netcdf4>=1.5.5,<1.6
  - pandas
  - pip
  - pooch
  - pre-commit
  - psutil
  - pydantic>=1.9
  - pyproj
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-mock
  - pytest-sugar
  - pytest-xdist
  - regionmask
  - s3fs
  - scipy
  - xarray-datatree
  - xgcm
  - zarr>=2.10
  - pip:
      - git+https://github.com/intake/intake.git
      - git+https://github.com/pydata/xarray.git
      - git+https://github.com/jbusecke/xmip.git
