name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - boto3
  - cftime
  - codecov
  - fastprogress>= 0.2.6
  - h5netcdf>=0.8.1
  - ipython
  - netcdf4>=1.5.3
  - pip
  - pre-commit
  - psutil
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-xdist
  - scipy
  - toolz
  - zarr>=2.4
  - pip:
      - git+https://github.com/intake/filesystem_spec.git
      - git+https://github.com/intake/intake.git
      - git+https://github.com/dask/gcsfs.git
      - git+https://github.com/dask/s3fs.git
      - git+https://github.com/pydata/xarray.git
      - git+https://github.com/jbusecke/cmip6_preprocessing.git
