name: intake-esm-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - cftime
  - codecov
  - dask >=2024.12
  - fastprogress >=1.0.0
  - flaky >= 3.8.0
  - gcsfs >=2024.12
  - h5netcdf >=0.8.1
  - ipython
  - itables
  - matplotlib
  - netcdf4 >=1.5.5,!=1.6.1
  - pandas >=2.1.0
  - pip
  - polars>=1.24.0,<1.33.0
  - pooch
  - pre-commit
  - psutil
  - pydantic >=2.0
  - pydap !=3.5.5
  - pyproj
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-mock
  - pytest-sugar
  - pytest-xdist
  - regionmask
  - s3fs >=2024.12
  - setuptools >=75.0.0
  - setuptools_scm >=8.1.0
  - scipy
  - xarray-datatree
  - xgcm
  - zarr <3.0|>=3.0.10
  - kerchunk >=0.2.9
  - pip:
      - git+https://github.com/intake/intake.git
      - git+https://github.com/pydata/xarray.git
      - git+https://github.com/jbusecke/xmip.git
