name: intake-esm-dev
channels:
  - conda-forge
dependencies:
  - intake-xarray>=0.3.1
  - nbsphinx
  - numpydoc
  - python=3.7
  - pyyaml
  - sphinx_rtd_theme
  - tqdm
  - docrep
  - click
  - git
  - make
  - ipython
  - s3fs
  - fsspec
